- better init.d script with proper daemon status reporting;

diff --git a/files/usr/share/kafka/kafka.init b/files/usr/share/kafka/kafka.init
--- a/files/usr/share/kafka/kafka.init
+++ b/files/usr/share/kafka/kafka.init
@@ -6,96 +6,70 @@
 # Required-Stop:     $remote_fs $syslog
 # Default-Start:     2 3 4 5
 # Default-Stop:      0 1 6
-# Short-Description: Kafka broker
-# Description:       Kafka broker
+# Short-Description: Kafka server
+# Description:       Kafka server
 ### END INIT INFO
 
 NAME=kafka
-PID_FILE=/var/run/$NAME.pid
+DESC="Kafka server"
+USER=$NAME
+GROUP=$NAME
 
 DAEMON="/usr/share/kafka/bin/kafka-server-start.sh"
 DAEMON_OPTS="-daemon /etc/kafka/server.properties"
+PID_FILE=/var/run/$NAME.pid
 
-start() {
-  if [ -f $PID_FILE ]
-    then
-      PID=`cat $PID_FILE`
-      if [ -z "`ps -ef | awk '{print $2}' | grep "^$PID$"`" ]; then
-        echo "\n$PID_FILE exists but the process is not running. Deleting $PID_FILE and retrying"
-        rm -f $PID_FILE
-        start
-      else
-        echo "\n$PID_FILE exists, process is already running"
-        exit 0
-      fi
-    else
-        # run under non-root user
-        su $NAME -s /bin/bash -c "$DAEMON $DAEMON_OPTS"
-        sleep 2
-        PID=`ps ax | grep -E '[k]afka.Kafka' | awk '{print $1}'`
-        if [ -z "`printf '%s' "$PID" | tr -d [:space:]`" ]; then
-          rm -f $PID_FILE
-          echo "\nCould not start $NAME"
-        else
-          echo $PID > $PID_FILE;
-          echo "\n$NAME started"
-        fi
-    fi
-}
-
-stop() {
-  if [ ! -f $PID_FILE ]
-  then
-    echo "\n$PID_FILE does not exist, process is not running"
-    return 1
-  else
-    kill `cat $PID_FILE`;
-    rm -f $PID_FILE;
-    echo "\n$NAME stopped"
-    return 0
-  fi
-}
-
-status() {
-  if [ -f $PID_FILE ]
-  then
-    PID=`cat $PID_FILE`
-    if [ -z "`ps -ef | awk '{print $2}' | grep "^$PID$"`" ]
-    then
-      echo "$NAME stopped but pid file exists"
-      exit 1
-    else
-      echo "$NAME running with pid $PID"
-      exit 0
-    fi
-  else
-    echo "$NAME stopped"
-    exit 1
-  fi
-}
+PATH=/sbin:/usr/sbin:/bin:/usr/bin
+. /lib/lsb/init-functions
+[ -r /etc/default/rcS ] && . /etc/default/rcS
+[ -r /etc/default/$NAME ] && . /etc/default/$NAME
 
 case "$1" in
-  status)
-    status
-  ;;
   start)
-    echo -n "Starting daemon: "$NAME
-    start
-  ;;
-  stop)
-    echo -n "Stopping daemon: "$NAME
-    stop
-  ;;
-  restart)
-    echo -n "Restarting daemon: "$NAME
-    stop
-    sleep 2
-    start
-  ;;
+    log_daemon_msg "Starting $DESC"
 
+    pid=$( pidofproc -p $PID_FILE $NAME)
+    if [ -n "$pid" ] ; then
+      log_begin_msg "Already running."
+      log_end_msg 0
+      exit 0
+    fi
+
+    start-stop-daemon --start -b --user "$USER" -c "$USER" --pidfile "$PID_FILE" --exec $DAEMON -- $DAEMON_OPTS
+    log_end_msg $?
+    ;;
+  stop)
+    log_daemon_msg "Stopping $DESC"
+
+    if [ -f "$PID_FILE" ]; then 
+      start-stop-daemon --stop --pidfile "$PID_FILE" --user "$USER" --retry=TERM/20/KILL/5 >/dev/null
+      if [ $? -eq 1 ]; then
+        log_progress_msg "$DESC is not running but pid file exists, cleaning up"
+      elif [ $? -eq 3 ]; then
+        PID="`cat $PID_FILE`"
+        log_failure_msg "Failed to stop $DESC (pid $PID)"
+        exit 1
+      fi
+      rm -f "$PID_FILE"
+    else
+      log_progress_msg "(not running)"
+    fi
+    log_end_msg 0
+    ;;
+  status)
+    status_of_proc -p $PID_FILE "$NAME" "$NAME" && exit 0 || exit $?
+    ;;
+  restart|force-reload)
+    if [ -f "$PID_FILE" ]; then
+      $0 stop
+      sleep 1
+    fi
+    $0 start
+    ;;
   *)
-  echo "Usage: "$1" {status|start|stop|restart}"
-  exit 1
+    log_success_msg "Usage: $0 {start|stop|status|restart|force-reload}"
+    exit 1
+    ;;
 esac
 
 exit 0
